# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'dailymeditation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dailymeditation
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  

  pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

end